# Supports PlaceholderAPI
settings:
  # Spawns fireworks upon a player joining!
  update-notifications:
    disable: false

  welcome-fireworks:
    disable: false

    # The amount of fireworks that should spawn
    amount: 5

  # Sends a title to the player upon joining!
  welcome-title:
    disable: false

    # ":" splits the Title, and the Subtitle!
    message: "&e&lWelcome:&6Welcome"

  # Sends a motd message to the player upon joining!
  motd-message:
    disable: false

    # Supports PlaceholderAPI
    message: "&eWelcome to the server, &6%player_name%&e!"