name: SpareLobby
version: ${project.version}
main: me.tofpu.sparelobby.SpareLobby
api-version: 1.13
authors: [ Tofpu ]
softdepend:
  - PlaceholderAPI
commands:
  sparelobby:
    aliases:
      - sl
      - slobby
    permission: sparelobby.use

