# --------------------------
# SUPPORTS PlaceHolderAPI

settings:
  welcome-title:
    disable: false # IF DISABLED, PLAYER WON'T RECEIVE THE TITLE
    message: "&e&lWelcome:&6Welcome"

  motd-message:
    disable: false # IF DISABLED, PLAYER WON'T RECEIVE THE MOTD MESSAGE
    message: "&e%player_name% &6has joined the server&e!"